website/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)

    from website.main.routes import main
    from website.portfolio.routes import portfolios

    app.register_blueprint(main)
    app.register_blueprint(portfolios)

    return app

website/main/routes.py
from flask import Blueprint, render_template


main = Blueprint("main", __name__)


@main.route("/home")
@main.route("/")
def home():
    return render_template("index.html", title="Home")

website/portfolio/routes.py
from flask import Blueprint, render_template


portfolios = Blueprint("portfolios", __name__)


@portfolios.route("/portfolio")
def portfolio():
    return render_template("portfolio.html", title="Portfolio")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% if title %}
    <title>Aian Vergara - {{ title }}</title>
    {% else %}
    <title>Cris-aian Vergara</title>
    {% endif %}

    <!-- Favicon -->
    <link
      rel="icon"
      href="{{ url_for('static', filename='img/favicon.png') }}"
    />
    <!-- Bootstrap 5 -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
    />
    <!-- My CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body>
    <main class="container">{% block content %} {% endblock %}</main>
    {% if title == "Home" %}
    <footer class="text-center fixed-bottom">
      <ul class="m-0 p-0">
        <li class="d-inline-block">
          <a href="https://www.linkedin.com/in/crisaianvergara/" target="_blank"
            ><i class="fa-brands fa-linkedin fa-2x"></i
          ></a>
        </li>
        <li class="d-inline-block">
          <a href="https://github.com/crisaianvergara" target="_blank"
            ><i class="fa-brands fa-square-github fa-2x"></i
          ></a>
        </li>
        <li class="d-inline-block">
          <a href="https://github.com/crisaianvergara" target="_blank"
            ><i class="fa-brands fa-square-facebook fa-2x"></i
          ></a>
        </li>
        <li class="d-inline-block">
          <a href="https://twitter.com/The21stKuruno" target="_blank"
            ><i class="fa-brands fa-square-twitter fa-2x"></i
          ></a>
        </li>
        <li class="d-inline-block">
          <a href="https://www.instagram.com/aian.vergara/" target="_blank"
            ><i class="fa-brands fa-square-instagram fa-2x"></i
          ></a>
        </li>
        <li class="d-inline-block">
          <a href="https://www.instagram.com/aian.vergara/" target="_blank"
            ><i class="fa-solid fa-square-envelope fa-2x"></i
          ></a>
        </li>
      </ul>
    </footer>
    {% endif %}
    <!-- Fontawesome -->
    <script
      src="https://kit.fontawesome.com/543a846626.js"
      crossorigin="anonymous"
    ></script>
    <!-- Anime JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <!-- My JS -->
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  </body>
</html>

website/templates/index.html
{% extends "base.html" %} {% block content %}
<section class="section-home">
  <div class="text-center">
    <h1>Cris-aian Vergara</h1>
    <div class="ml10">
      <h4 class="letters">Python Developer</h4>
    </div>
    <address>
      <i class="fa-solid fa-location-dot me-1"></i> Cagayan, Philippines
    </address>
    <a
      href="{{ url_for('portfolios.portfolio') }}"
      class="btn btn-light mx-1 rounded-0"
      >Portfolio</a
    >
    <button class="btn btn-outline-light mx-1 rounded-0">Resume</button>
  </div>
</section>
{% endblock %}

website/templates/portfolio.html
{% extends "base.html" %} {% block content %}
<section class="section-portfolio">
  <div class="d-flex flex-row flex-wrap justify-content-center">
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Kris Kap</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Sulat Aian</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Online Payroll</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Weather App</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Social Network</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Quiz Wapp</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Snake Game</h5>
      </div>
    </div>
    <div class="card border-0 m-4 bg-transparent" style="width: 16rem">
      <div class="card-body">
        <img
          src="https://images.pexels.com/photos/2028261/pexels-photo-2028261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          class="card-img-top rounded-0"
          alt=""
        />
      </div>
      <div class="card-footer">
        <h5 class="card-title mb-0">Tetris</h5>
      </div>
    </div>
  </div>
</section>
{% endblock %}